Retry on empty $resources

diff --git a/.github/workflows/tap-pr.yml b/.github/workflows/tap-pr.yml
--- a/.github/workflows/tap-pr.yml
+++ b/.github/workflows/tap-pr.yml
@@ -42,8 +42,8 @@ jobs:
       run: |
         while true; do
           resources=$(kubectl -n ${{ env.WORKLOAD_NAMESPACE }} get workload ${{ env.FORMATTED_WORKLOAD_NAME }} -o jsonpath='{.status.resources}')
-          if [ $? -ne 0 ]; then
-            echo "::error::Failed to get resources, retrying in 15s..."
+          if [ $? -ne 0 ] || [ -z "$resources" ]; then
+            echo "::error::Failed to get resources or resources are empty, retrying in 15s..."
             sleep 15
             continue
           fi
@@ -71,8 +71,8 @@ jobs:
       run: |
         while true; do
           resources=$(kubectl -n ${{ env.WORKLOAD_NAMESPACE }} get workload ${{ env.FORMATTED_WORKLOAD_NAME }} -o jsonpath='{.status.resources}')
-          if [ $? -ne 0 ]; then
-            echo "::error::Failed to get resources, retrying in 15s..."
+          if [ $? -ne 0 ] || [ -z "$resources" ]; then
+            echo "::error::Failed to get resources or resources are empty, retrying in 15s..."
             sleep 15
             continue
           fi
